import React, { useEffect, useState } from 'react';
import { api } from './api.js';

export function AuthGate({ children }) {
  const [session, setSession] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function refresh() {
    try { setSession(await api('/api/auth/session')); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); }
  }
  useEffect(() => {
    refresh();
    const expired = () => { setSession({ user: null, setupRequired: false }); setError('Your session has expired. Please log in again.'); };
    window.addEventListener('session-expired', expired);
    return () => window.removeEventListener('session-expired', expired);
  }, []);
  if (session?.user) return children({ user: session.user, refresh, logout: async () => { await api('/api/auth/logout', { method: 'POST' }); setSession({ user: null, setupRequired: false }); } });
  const setup = session?.setupRequired;
  return <div className="auth-page"><section className="auth-card"><a href="/" className="auth-brand">Palletshipper<span>.</span></a><p className="eyebrow">{setup ? 'FIRST-TIME SETUP' : 'YOUR WORKSPACE'}</p><h1>{loading ? 'Loading…' : setup ? 'Create your administrator account.' : 'Welcome back.'}</h1><p className="auth-intro">{setup ? 'Use this account to manage users and shipment access.' : 'Log in to manage your shipments and equipment.'}</p>{!loading && <form onSubmit={async e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); setBusy(true); setError(''); try { setSession(await api(setup ? '/api/auth/setup' : '/api/auth/login', { method: 'POST', body })); } catch (e) { setError(e.message); } finally { setBusy(false); } }}>
    {setup && <><label>Setup code<input name="setupToken" type="password" autoComplete="off" required/></label><p className="form-hint">Use the code in data/setup-token.txt or the SETUP_TOKEN variable on Railway.</p><label>Name<input name="name" autoComplete="name" required maxLength="200"/></label></>}
    <label>Email address<input name="email" type="email" autoComplete="username" required maxLength="254"/></label><label>Password<input name="password" type="password" autoComplete={setup ? 'new-password' : 'current-password'} minLength={setup ? 12 : undefined} maxLength="256" required/></label>{setup && <p className="form-hint">Use at least 12 characters.</p>}{error && <p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy || !session}>{busy ? 'Please wait…' : setup ? 'Create administrator account' : 'Log in'}</button>{!session && <button type="button" className="secondary" onClick={refresh}>Try again</button>}
    </form>}</section></div>;
}

export function UserManager({ onAccountUpdated }) {
  const [users, setUsers] = useState([]), [editing, setEditing] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function load() { setUsers(await api('/api/users')); }
  useEffect(() => { load().catch(e => setError(e.message)); }, []);
  return <div className="user-management"><p className="import-explanation">Administrators can see all shipments. Other users can see their own and assigned shipments.</p><div className="user-list">{users.map(user => <div className="user-row" key={user.id}><div><strong>{user.name}</strong><span>{user.email}</span></div><span className="user-role">{user.role === 'admin' ? 'Administrator' : 'User'}{!user.active && ' · Inactive'}</span><button className="secondary" disabled={busy} onClick={() => { setEditing(user); setError(''); }}>Edit</button></div>)}</div><div className="user-form-heading"><h3>{editing ? `Account for ${editing.name}` : 'Add user'}</h3>{editing && <button className="secondary" onClick={() => { setEditing(null); setError(''); }}>New account</button>}</div><form key={editing?.id || 'new'} onSubmit={async e => {
    e.preventDefault(); const form = e.currentTarget, body = Object.fromEntries(new FormData(form));
    if (editing) { body.active = body.active === 'on'; if (!body.password) delete body.password; }
    setBusy(true); setError('');
    try { await api(editing ? `/api/users/${editing.id}` : '/api/users', { method: editing ? 'PATCH' : 'POST', body }); setEditing(null); form.reset(); await onAccountUpdated(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); }
  }}><div className="form-grid"><label>Name<input name="name" required maxLength="200" defaultValue={editing?.name || ''}/></label><label>Email address<input name="email" type="email" required maxLength="254" defaultValue={editing?.email || ''}/></label></div><div className="form-grid"><label>Role<select name="role" defaultValue={editing?.role || 'member'}><option value="member">User</option><option value="admin">Administrator</option></select></label><label>{editing ? 'New password (optional)' : 'Password'}<input name="password" type="password" autoComplete="new-password" minLength="12" maxLength="256" required={!editing}/></label></div>{editing && <label className="check-label"><input name="active" type="checkbox" defaultChecked={editing.active}/> Account active</label>}<p className="form-hint">Changing a password or deactivating an account ends existing sessions.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="primary" disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create user'}</button></div></form></div>;
}

export function ShipmentAccess({ shipment, close }) {
  const [access, setAccess] = useState(null), [selected, setSelected] = useState([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { api(`/api/shipments/${shipment.id}/access`).then(result => { setAccess(result); setSelected(result.userIds.filter(id => result.users.some(u => u.id === id && u.active))); }).catch(e => setError(e.message)); }, [shipment.id]);
  return <div><p className="import-explanation">Select who can view and update this shipment. Administrators and the creator always have access.</p>{access?.owner && <div className="access-owner">Creator: <strong>{access.owner.name}</strong></div>}{!access && !error && <p>Loading users…</p>}<div className="access-list">{access?.users.filter(u => u.active).map(user => {
    const fixed = user.role === 'admin' || user.id === access.owner?.id;
    return <label className="access-user" key={user.id}><input type="checkbox" checked={fixed || selected.includes(user.id)} disabled={fixed || busy} onChange={e => setSelected(current => e.target.checked ? [...current, user.id] : current.filter(id => id !== user.id))}/><span><strong>{user.name}</strong><small>{user.email}</small></span><em>{fixed ? 'Always has access' : ''}</em></label>;
  })}</div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="secondary" disabled={busy} onClick={close}>Cancel</button><button className="primary" disabled={busy || !access} onClick={async () => { setBusy(true); setError(''); try { await api(`/api/shipments/${shipment.id}/access`, { method: 'PUT', body: { userIds: selected } }); close(); } catch (e) { setError(e.message); } finally { setBusy(false); } }}>{busy ? 'Saving…' : 'Save access'}</button></div></div>;
}

export function PasswordForm({ onAccountUpdated, close, user }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  return <><section className="settings-section"><h3>Profile and challenge</h3><form onSubmit={async e => { e.preventDefault(); const values = new FormData(e.currentTarget); setBusy(true); setError(''); try { await api('/api/auth/profile', { method: 'PATCH', body: { nickname: values.get('nickname'), challengeParticipating: values.get('challengeParticipating') === 'on' } }); await onAccountUpdated(); close(); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><label>Nickname<input name="nickname" maxLength="40" autoComplete="nickname" defaultValue={user.nickname || ''} disabled={busy}/></label><p className="form-hint">Shown in the Transport Challenge. Leave empty to use your account name. Your account name and login stay the same.</p><label className="checkbox-label"><input name="challengeParticipating" type="checkbox" defaultChecked={user.challengeParticipating} disabled={busy}/> Participate in the Transport Challenge</label><p className="form-hint">Participation is optional. Opting out hides you from rankings and rewards without affecting shipment access or tracking. Rejoining restores your recorded scores.</p><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save profile'}</button></form></section><section className="settings-section"><h3>Change password</h3><form onSubmit={async e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); setBusy(true); setError(''); try { await api('/api/auth/password', { method: 'POST', body }); await onAccountUpdated(); close(); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required maxLength="256"/></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength="12" maxLength="256" required/></label><p className="form-hint">At least 12 characters. Other sessions will be signed out.</p><div className="modal-footer"><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Change password'}</button></div></form></section>{error && <p className="form-error" role="alert">{error}</p>}</>;
}
