import React, { useEffect, useState } from 'react';
import { api } from './api.js';
import { AddressField } from './new-shipment.jsx';
const number = value => new Intl.NumberFormat('en-GB', { maximumFractionDigits: 1 }).format(value || 0);
export function Challenges({ user }) {
  const currentYear = Number(new Intl.DateTimeFormat('en', { timeZone: 'Europe/Brussels', year: 'numeric' }).format(new Date()));
  const [year, setYear] = useState(currentYear), [month, setMonth] = useState(''), [metric, setMetric] = useState('checks');
  const [data, setData] = useState(null), [settings, setSettings] = useState(null), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  async function load() { const [board, config] = await Promise.all([api(`/api/challenges?year=${year}${month ? `&month=${month}` : ''}`), api('/api/challenges/settings')]); setData(board); setSettings(config); }
  useEffect(() => { let ignore = false; setData(null); Promise.all([api(`/api/challenges?year=${year}${month ? `&month=${month}` : ''}`), api('/api/challenges/settings')]).then(([board, config]) => { if (!ignore) { setData(board); setSettings(config); } }).catch(e => { if (!ignore) setError(e.message); }); return () => { ignore = true; }; }, [year, month]);
  async function run(action) { setBusy(true); setError(''); setMessage(''); try { await action(); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  const ranking = [...(data?.rows || [])].sort((a,b) => b[metric] - a[metric] || a.name.localeCompare(b.name));
  const me = ranking.find(row => row.id === user.id), rank = me ? 1 + ranking.filter(row => row[metric] > me[metric]).length : null;
  const labels = { checks: 'Shipment Finisher', pallets: 'Pallet Champion', palletKm: 'Distance Champion' };
  const units = { checks: 'pallet checks', pallets: 'arrival confirmations', palletKm: 'pallet km' };
  return <div className="challenge-content">
    <p className="import-explanation">Every pallet check counts once. Item checks do not count. Outbound and return distance rewards go to the user with the most pallet checks on that leg; ties share the reward. Corrections update scores.</p>
    {error && <p className="form-error" role="alert">{error}</p>}{message && <p className="warning" role="status">{message}</p>}
    <div className="challenge-filters"><label>Year<select value={year} onChange={e => setYear(Number(e.target.value))}>{[...new Set([year, ...(data?.years || [currentYear])])].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}</select></label><label>Period<select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Whole year</option>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Intl.DateTimeFormat('en',{month:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2026,i,1)))}</option>)}</select></label><label>Challenge<select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="secondary" disabled={busy || !data} onClick={()=>run(load)}>Refresh scores</button></div>
    {!data ? <p role="status">Loading challenges…</p> : <>
      <p className="form-hint">{data.shared ? 'Shared leaderboard: names and totals across all shipments. Shipment details remain restricted by access.' : 'This leaderboard includes only shipments you can access.'}</p>
      <div className="challenge-podium">{ranking.filter(r=>r[metric]>0).slice(0,3).map((row,index)=><article key={row.id}><span className="challenge-medal">{['🥇','🥈','🥉'][index]}</span><h3>{row.name}</h3><strong>{number(row[metric])}</strong><span>{units[metric]}</span></article>)}</div>
      <div className="challenge-personal">{!data.participating ? <><h3>Not participating</h3><p>Enable Participate in the Transport Challenge in your account settings to join. Click your account name to open them.</p></> : <><h3>Your progress</h3><p>{me?.[metric] ? `Rank ${rank} · ${number(me[metric])} ${units[metric]}` : 'Your first pallet check starts your challenge.'}</p><div className="challenge-badges">{me?.badges.map(b=><span key={b}>{b}</span>)}</div><label>Next check badge: {Math.min(me?.checks || 0,100)} / 100<progress max="100" value={Math.min(me?.checks || 0,100)}/></label></>}</div>
      <div className="table-scroll"><table><thead><tr><th>Rank</th><th>User</th><th>Pallet checks</th><th>Arrivals</th><th>Pallet km</th></tr></thead><tbody>{ranking.map(row=><tr key={row.id} className={row.id===user.id?'challenge-current':''}><td>{row[metric]>0 ? 1+ranking.filter(r=>r[metric]>row[metric]).length:'—'}</td><td>{row.name}{row.id===user.id?' (you)':''}</td><td>{row.checks}</td><td>{row.pallets}</td><td>{number(row.palletKm)}{row.provisionalKm>0 && <small className="challenge-provisional">{number(row.provisionalKm)} provisional</small>}</td></tr>)}</tbody></table></div>
      {!!data.transports.length && <section className="settings-section"><h3>Transport rewards</h3>{data.transports.map(t=><div className="challenge-transport" key={t.shipmentId+t.leg}><strong>{t.name} · {t.leg === 'outbound'?'Outbound':'Return'}</strong><p>{t.arrived} arrivals in this period · {t.distanceKm===null?'Distance not set':`${number(t.distanceKm)} km per pallet · ${number(t.palletKm)} pallet km`} · {t.completed?'Complete':'Provisional'}</p><small>{t.winners.length ? t.winners.map(w=>w.name).join(' + ') : 'No participating users'}{t.winners.length>1?' · equally shared':''}</small></div>)}</section>}
      <p className="form-hint">Scores use Belgian calendar dates. Old checks without a recorded user earn no points. Rechecking restores the original credit. Archiving keeps scores; deleting pallets or shipments removes their scores. Automatic pallet kilometres use straight-line distances rounded to whole kilometres. These are game estimates, not actual transport distances.</p>
    </>}
    {user.role==='admin' && settings && <section className="settings-section"><h3>Challenge settings</h3><form onSubmit={e=>{e.preventDefault(); const form=new FormData(e.currentTarget);run(async()=>{await api('/api/challenges/settings',{method:'PUT',body:{warehouseAddress:form.get('warehouseAddress'),shared:form.get('shared')==='on'}});await load();setMessage('Challenge settings saved.');});}}><label>Default warehouse address<input name="warehouseAddress" maxLength="500" defaultValue={settings.warehouseAddress} placeholder="Street, number, postcode, town, country"/></label><label className="checkbox-label"><input type="checkbox" name="shared" defaultChecked={settings.shared}/> Share user names and total scores across all shipments</label><button className="primary" disabled={busy}>Save challenge settings</button></form><p className="form-hint">{settings.routingConfigured?'Address search configured. Test the connection to verify the key.':'ORS_API_KEY is not configured. Manual distances are available.'}</p><button className="secondary" disabled={busy || !settings.routingConfigured} onClick={()=>run(async()=>{const result=await api('/api/routing/check',{method:'POST',body:{}});setMessage(result.message);})}>{busy?'Working…':'Test route connection'}</button></section>}
  </div>;
}
export function TransportRoute({ shipment, onSaved }) {
  const [warehouse, setWarehouse] = useState({address:shipment.warehouseAddress || '',coordinates:shipment.warehouseCoordinates?JSON.parse(shipment.warehouseCoordinates):null});
  const [outbound, setOutbound] = useState({address:shipment.outboundAddress || '',coordinates:shipment.outboundCoordinates?JSON.parse(shipment.outboundCoordinates):null});
  const [distances, setDistances] = useState({outboundKm:shipment.outboundKm??'',returnKm:shipment.returnKm??''});
  const [busy, setBusy] = useState(false), [error,setError]=useState(''), [config,setConfig]=useState(null), [message,setMessage]=useState('');
  useEffect(()=>{let ignore=false;api('/api/challenges/settings').then(value=>{if(ignore)return;setConfig(value);if(!shipment.warehouseAddress)setWarehouse(w=>({...w,address:value.warehouseAddress}));}).catch(e=>{if(!ignore)setError(e.message);});return()=>{ignore=true;};},[shipment.id]);
  async function run(action){setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function save(calculate){const body={revision:shipment.revision,warehouseAddress:warehouse.address,outboundAddress:outbound.address,warehouseCoordinates:warehouse.coordinates,outboundCoordinates:outbound.coordinates,calculate,...Object.fromEntries(Object.entries(distances).map(([key,v])=>[key,v===''?null:Number(v)]))};const updated=await api(`/api/shipments/${shipment.id}/route`,{method:'PUT',body});setDistances({outboundKm:updated.outboundKm??'',returnKm:updated.returnKm??''});onSaved(updated);setMessage(calculate?'Straight-line distance calculated and saved for outbound and return.':'Route and manual distances saved.');}
  return <section className="settings-section"><h3>Transport addresses and distances</h3><p className="import-explanation">These addresses are used only for challenge scores, never on labels or reports. The warehouse is both the departure and return location. Select both address matches to calculate the straight-line distance. Outbound and return use the same distance, rounded to whole kilometres. This estimate works worldwide for the challenge.</p>
    {[['warehouse','Warehouse / return address',warehouse],['outbound','Outbound address',outbound]].map(([key,label,value])=><AddressField key={key} label={label} value={value} configured={config?.routingConfigured} disabled={busy} onChange={match=>{(key==='warehouse'?setWarehouse:setOutbound)(match);setDistances({outboundKm:'',returnKm:''});}}/>)}
    <div className="form-grid">{[['outboundKm','Outbound distance (km)'],['returnKm','Return distance (km)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="50000" step="0.1" disabled={busy} value={distances[key]} onChange={e=>setDistances(d=>({...d,[key]:e.target.value}))}/></label>)}</div>
    {shipment.distanceSource && <p className="form-hint">Saved distance source: {shipment.distanceSource==='straight-line'?'Straight-line distance':shipment.distanceSource==='openrouteservice'?'Previously saved driving distance':'Manual distance'}</p>}
    {error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-hint" role="status">{message}</p>}
    {!config?.routingConfigured && <p className="form-hint">Address search is not configured. Previously confirmed addresses can still calculate straight-line distances; manual distances are also available.</p>}
    <div className="route-actions"><button className="primary" disabled={busy || !warehouse.coordinates || !outbound.coordinates} onClick={()=>run(()=>save(true))}>{busy?'Working…':'Calculate and save distances'}</button><button className="secondary" disabled={busy || !warehouse.address.trim() || !outbound.address.trim()} onClick={()=>run(()=>save(false))}>Save manual route</button></div><p className="form-hint">Address search powered by openrouteservice / HeiGIT and OpenStreetMap contributors. Only address searches contact the service. Straight-line distances are calculated locally; manual corrections remain available.</p>
  </section>;
}
