import { formatDate } from '../shared/dates.js';
import React, { useEffect, useState, useCallback } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import { detectColumns } from '../shared/import-columns.js';
import { nextPalletNumber } from '../shared/numbering.js';

import { stages, defaultColumns } from '../shared/tracking.js';
import { PhotoViewer } from './photo-viewer.jsx';
import { PalletOverview } from './pallet-overview.jsx';
import { api } from './api.js';
import { AuthGate, UserManager, ShipmentAccess, PasswordForm } from './accounts.jsx';

function Icon({ type = 'box', size = 20 }) {
  const paths = { box: <><path d="m3 7 9-4 9 4-9 4-9-4Zm0 0v10l9 4 9-4V7M12 11v10M7 5l10 4"/></>, plus: <path d="M12 5v14M5 12h14"/>, upload: <><path d="M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5"/></>, camera: <><path d="M3 7h4l2-3h6l2 3h4v13H3Z"/><circle cx="12" cy="13" r="4"/></>, close: <path d="m6 6 12 12M18 6 6 18"/>, arrow: <path d="M5 12h14m-5-5 5 5-5 5"/> };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[type]}</svg>;
}
function HeaderLogo({ source, shipmentName }) {
  const [failed, setFailed] = useState(false);
  return <div className="header-brand">{source && !failed ? <img src={source} alt={`Logo van ${shipmentName}`} onError={() => setFailed(true)}/> : <span className="brand"><span className="brand-icon"><Icon size={25}/></span>Palletshipper<span className="brand-dot">.</span></span>}</div>;
}
function Modal({ title, children, close, wide }) {
  return <div className="overlay" onClick={e => { if (e.target === e.currentTarget) close(); }}><section className={`modal ${wide ? 'wide' : ''}`} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Sluiten"><Icon type="close"/></button></header>{children}</section></div>;
}
const nameCollator = new Intl.Collator('nl-BE', { numeric: true, sensitivity: 'base' });
const searchText = value => String(value || '').normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase();

function App({ user, logout, refresh }) {
  const [shipments, setShipments] = useState([]), [selected, setSelected] = useState(''), [data, setData] = useState({ pallets: [], items: [] });
  const [pallet, setPallet] = useState('all'), [search, setSearch] = useState(''), [modal, setModal] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true);
  const [preview, setPreview] = useState(null), [importRows, setImportRows] = useState([]), [columns, setColumns] = useState({ name: 0, code: -1, quantity: -1 }), [hasHeader, setHasHeader] = useState(true);
  const [palletQuantity, setPalletQuantity] = useState(1);
  const [editingItem, setEditingItem] = useState(null);
  const [logoVersion, setLogoVersion] = useState(0);
  const [editingPallet, setEditingPallet] = useState(null);
  const [viewingPhoto, setViewingPhoto] = useState(null);
  const closePhotoViewer = useCallback(() => setViewingPhoto(null), []);
  const [deletingPhoto, setDeletingPhoto] = useState(null);
  const [showArchived, setShowArchived] = useState(false);
  const [view, setView] = useState('items');
  const [sortOrder, setSortOrder] = useState('nameAsc');
  const shipmentStorageKey = `palletshipper:last-shipment:${user.id}`;
  const listedShipments = shipments.filter(s => !!s.archivedAt === showArchived);
  const shipment = shipments.find(s => s.id === selected);
  const unassigned = data.items.filter(i => !i.palletId).length;
  const searchTerms = searchText(search).trim().split(/\s+/).filter(Boolean);
  const filtered = data.items.filter(item => {
    const inPallet = pallet === 'all' || (pallet === 'unassigned' ? !item.palletId : item.palletId === pallet);
    const text = searchText(`${item.displayName} ${item.code} ${item.note}`);
    return inPallet && searchTerms.every(term => text.includes(term));
  });
  if (sortOrder !== 'added') filtered.sort((a, b) => nameCollator.compare(a.displayName, b.displayName) * (sortOrder === 'nameDesc' ? -1 : 1));
  const activePallet = data.pallets.find(p => p.id === pallet);
  const visibleStages = stages.filter(([key]) => (data.columns || defaultColumns)[key]);
  const run = async (task) => { setBusy(true); setError(''); try { await task(); } catch (e) { if (e.status === 409) { try { await reload(); setShipments(await api('/api/shipments')); } catch {} } setError(e.message); } finally { setBusy(false); } };
  async function reload(id = selected) { if (id) setData(await api(`/api/shipments/${id}`)); }
  useEffect(() => {
    api('/api/shipments').then(rows => {
      setShipments(rows);
      let remembered;
      try { remembered = localStorage.getItem(shipmentStorageKey); } catch {}
      const first = rows.find(s => s.id === remembered) || rows.find(s => !s.archivedAt) || rows[0];
      if (first) { setShowArchived(!!first.archivedAt); setSelected(first.id); }
    }).catch(e => setError(e.message)).finally(() => setLoading(false));
  }, []);
  useEffect(() => {
    if (!selected) return;
    try { localStorage.setItem(shipmentStorageKey, selected); } catch {}
  }, [selected, shipmentStorageKey]);
  useEffect(() => { if (!selected) return; let ignore = false; setLoading(true); setData({ pallets: [], items: [] }); api(`/api/shipments/${selected}`).then(result => { if (!ignore) setData(result); }).catch(e => { if (!ignore) setError(e.message); }).finally(() => { if (!ignore) setLoading(false); }); return () => { ignore = true; }; }, [selected]);
  useEffect(() => {
    if (busy || modal || loading) return;
    let cancelled = false, inFlight = false;
    async function synchronize() {
      if (document.hidden || inFlight) return;
      inFlight = true;
      try {
        const rows = await api('/api/shipments');
        const current = rows.find(s => s.id === selected);
        const detail = current ? await api(`/api/shipments/${selected}`) : null;
        if (cancelled) return;
        setShipments(rows);
        if (current) { setShowArchived(!!current.archivedAt); setData(detail); setPallet(value => value === 'all' || value === 'unassigned' || detail.pallets.some(p => p.id === value) ? value : 'unassigned'); }
        else if (selected || rows.length) { const first = rows.find(s => !s.archivedAt) || rows[0]; setShowArchived(!!first?.archivedAt); changeShipment(first?.id || ''); setData({ pallets: [], items: [] }); }
      } catch (e) { if (!cancelled && e.status === 404) setError('Deze shipment is niet meer beschikbaar.'); }
      finally { inFlight = false; }
    }
    const timer = setInterval(synchronize, 5000);
    window.addEventListener('focus', synchronize);
    document.addEventListener('visibilitychange', synchronize);
    return () => { cancelled = true; clearInterval(timer); window.removeEventListener('focus', synchronize); document.removeEventListener('visibilitychange', synchronize); };
  }, [selected, busy, modal, loading]);
  function changeShipment(id) { setSelected(id); setPallet('all'); setSearch(''); }
  function toggleArchiveView(archived) {
    setShowArchived(archived); changeShipment(shipments.find(s => !!s.archivedAt === archived)?.id || '');
  }
  async function refreshShipments(archived = showArchived) {
    const rows = await api('/api/shipments'); setShipments(rows); setShowArchived(archived);
    changeShipment(rows.find(s => !!s.archivedAt === archived)?.id || '');
  }
  function openPalletModal() { setPalletQuantity(1); setError(''); setModal('pallet'); }
  function mapImport(source, mapping, header) {
    setImportRows(source.rows.slice(header ? 1 : 0).map(row => ({ name: row[mapping.name] || '', code: row[mapping.code] || '', quantity: mapping.quantity < 0 ? 1 : (row[mapping.quantity] || ''), note: '' })));
  }
  async function loadImport(file) {
    if (!file) return;
    await run(async () => {
      const body = new FormData(); body.append('file', file);
      const result = await api('/api/import-preview', { method: 'POST', body });
      const header = result.hasHeader ?? !result.pdf;
      const detected = result.columns || detectColumns(result.rows[0]);
      const mapping = { ...detected, name: detected.name < 0 ? 0 : detected.name };
      setPreview(result); setColumns(mapping); setHasHeader(header); mapImport(result, mapping, header); setModal('import');
    });
  }
  function updateMapping(key, value) { const next = { ...columns, [key]: Number(value) }; setColumns(next); mapImport(preview, next, hasHeader); }
  async function patchItem(id, body) {
    const previous = data.items.find(i => i.id === id);
    const optimistic = 'status' in body ? { ...previous, statuses: { ...previous.statuses, [body.status]: body.checked ? new Date().toISOString() : null } } : { ...previous, palletId: body.palletId };
    const replace = item => setData(current => ({ ...current, items: current.items.map(i => i.id === id ? item : i) }));
    replace(optimistic);
    await run(async () => { try { replace(await api(`/api/items/${id}`, { method: 'PATCH', body: { ...body, revision: previous.revision } })); } catch (e) { replace(previous); throw e; } });
  }
  async function patchPallet(id, body) {
    const previous = data.pallets.find(p => p.id === id);
    const replace = pallet => setData(current => ({ ...current, pallets: current.pallets.map(p => p.id === id ? pallet : p) }));
    replace({ ...previous, statuses: { ...previous.statuses, [body.status]: body.checked ? new Date().toISOString() : null } });
    await run(async () => { try { replace(await api(`/api/pallets/${id}`, { method: 'PATCH', body: { ...body, revision: previous.revision } })); } catch (e) { replace(previous); throw e; } });
  }
  function openItemModal(item, action) { setEditingItem(item); setError(''); setModal(action); }
  async function addPhotos(palletId, files) {
    if (!files.length) return;
    await run(async () => {
      if (files.length > 10) throw new Error('Selecteer maximaal 10 foto’s tegelijk.');
      if (files.some(file => file.size > 15 * 1024 * 1024)) throw new Error('Elke foto mag maximaal 15 MB zijn.');
      const body = new FormData(); files.forEach(file => body.append('files', file));
      await api(`/api/pallets/${palletId}/photos`, { method: 'POST', body }); await reload();
    });
  }
  async function toggleColumn(key, checked, scope = 'items') {
    const field = scope === 'pallets' ? 'palletColumns' : 'columns';
    const previous = data[field] || defaultColumns;
    const columns = { ...previous, [key]: checked };
    setData(current => ({ ...current, [field]: columns }));
    await run(async () => { try { await api(`/api/shipments/${selected}/${scope === 'pallets' ? 'pallet-columns' : 'columns'}`, { method: 'PUT', body: { columns } }); } catch (e) { setData(current => ({ ...current, [field]: previous })); throw e; } });
  }
  const importTotal = importRows.reduce((n, row) => n + Number(row.quantity || 0), 0);
  return <div className="app-shell">
    <main><div className="topbar"><HeaderLogo key={`${selected}:${!!data.hasLogo}:${logoVersion}`} source={shipment && data.hasLogo ? `/api/shipments/${selected}/logo?v=${logoVersion}` : null} shipmentName={shipment?.name}/><div className="account-actions">{user.role === 'admin' && <button className="secondary" onClick={() => setModal('users')}>Gebruikersbeheer</button>}<button className="account-name" onClick={() => setModal('password')} title="Wachtwoord wijzigen">{user.name}</button><button className="secondary" disabled={busy} onClick={() => run(logout)}>Uitloggen</button></div></div>
      <div className="page-content"><div className="page-heading"><div><p className="eyebrow">OVERZICHT & OPVOLGING</p><h1>Alles klaar voor vertrek.</h1><p className="subtext">Stel je shipment samen en volg elk object van vertrek tot terugkomst.</p></div><div className="heading-actions"><button className="secondary" onClick={() => toggleArchiveView(!showArchived)}>{showArchived ? 'Actieve shipments' : 'Archief'}</button>{shipment && <button className="secondary" disabled={loading} onClick={() => setModal('export')}>Exporteren</button>}<button className="primary" onClick={() => setModal('shipment')}><Icon type="plus"/> Nieuwe shipment</button></div></div>
      {error && <div className="error" role="alert">{error}<button onClick={() => setError('')} aria-label="Melding sluiten">×</button></div>}
      {!shipment ? <section className="empty-start"><div className="empty-icon"><Icon size={42}/></div><p className="eyebrow">EEN GOEDE START</p><h2>{loading ? 'Shipments laden…' : showArchived ? 'Geen gearchiveerde shipments.' : 'Je eerste shipment begint hier.'}</h2><p>Maak een shipment aan, importeer je materiaal en verdeel het over je palletten.</p><button className="primary" onClick={() => setModal('shipment')}><Icon type="plus"/> Shipment aanmaken</button></section> : <>
      <section className="shipment-bar"><div><label htmlFor="shipment-select">{showArchived ? 'GEARCHIVEERDE SHIPMENT' : 'ACTIEVE SHIPMENT'}</label><select id="shipment-select" value={selected} onChange={e => changeShipment(e.target.value)}>{listedShipments.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="destination"><span>Outbound destination</span><strong>{shipment.destination || 'Niet opgegeven'}{shipment.outboundDate && ` · ${formatDate(shipment.outboundDate)}`}</strong></div><div className="destination"><span>Return destination</span><strong>{shipment.returnDestination || 'Niet opgegeven'}{shipment.returnDate && ` · ${formatDate(shipment.returnDate)}`}</strong></div>{shipment.canManage && <button className="secondary access-button" onClick={() => { setError(''); setModal('settings'); }}>Shipmentinstellingen</button>}<div className="shipment-created"><span>Aangemaakt</span><strong>{formatDate(shipment.createdAt)}</strong></div></section>
      <div className="stats"><div><span>Totaal objecten</span><strong>{data.items.length}<small>afzonderlijk opgevolgd</small></strong></div><div><span>Palletten</span><strong>{data.pallets.length}<small>in deze shipment</small></strong></div><div><span>Nog te verdelen</span><strong className={unassigned ? 'amber' : ''}>{unassigned}<small>objecten zonder pallet</small></strong></div><div><span>Terug in warehouse</span><strong>{data.items.filter(i => i.statuses.inWarehouse).length}<small>van {data.items.length} objecten</small></strong></div></div>
      <div className="shipment-views" role="group" aria-label="Shipmentweergave"><button className="secondary" aria-pressed={view === 'items'} onClick={() => setView('items')}>Objecten</button><button className="secondary" aria-pressed={view === 'pallets'} onClick={() => setView('pallets')}>Palletoverzicht</button></div>
      {view === 'pallets' ? <PalletOverview key={selected} pallets={data.pallets} items={data.items} columns={data.palletColumns || defaultColumns} onColumnChange={(key, checked) => toggleColumn(key, checked, 'pallets')} busy={busy} loading={loading} onEdit={p => { setEditingPallet(p); setError(''); setModal('renamePallet'); }} onDelete={p => { setEditingPallet(p); setError(''); setModal('deletePallet'); }} onStatusChange={patchPallet} onAdd={openPalletModal} onOpen={id => { setPallet(id); setSearch(''); setView('items'); }}/> : <div className="work-area"><section className="pallet-panel"><div className="panel-title"><h2>Palletten</h2><button className="icon-button" aria-label="Pallet toevoegen" onClick={openPalletModal} disabled={busy}><Icon type="plus"/></button></div><button className={`pallet-tab ${pallet === 'all' ? 'active' : ''}`} onClick={() => setPallet('all')}><span>Alle objecten</span><b>{data.items.length}</b></button><button className={`pallet-tab ${pallet === 'unassigned' ? 'active' : ''}`} onClick={() => setPallet('unassigned')}><span><i className="tiny-dot"/>Nog te verdelen</span><b>{unassigned}</b></button><div className="pallet-divider"/>{data.pallets.map(p => <button key={p.id} className={`pallet-tab pallet-entry ${pallet === p.id ? 'active' : ''}`} onClick={() => setPallet(p.id)}><span><Icon/>{p.name}{p.photo && <span title="Foto toegevoegd" className="photo-dot"/>}</span><b>{data.items.filter(i => i.palletId === p.id).length}</b></button>)}{!data.pallets.length && <p className="panel-help">Maak je eerste pallet aan om het materiaal te verdelen.</p>}<button className="add-pallet" onClick={openPalletModal}><Icon type="plus"/> Pallet toevoegen</button></section>
      <section className="materials-panel"><div className="materials-heading"><div><h2>{activePallet?.name || (pallet === 'unassigned' ? 'Nog te verdelen' : 'Alle objecten')} <span className="count-badge">{filtered.length}</span></h2><p>{activePallet ? 'Materiaal en transportstatus van deze pallet.' : 'Wijs materiaal toe en vink de status per object aan.'}</p></div><div className="actions"><label className={`button secondary ${busy ? 'disabled' : ''}`}><Icon type="upload"/> Importeren<input type="file" accept=".csv,.xlsx,.xls,.pdf" disabled={busy} onChange={e => { loadImport(e.target.files[0]); e.target.value = ''; }}/></label><button className="primary" onClick={() => setModal('item')} disabled={busy}><Icon type="plus"/> Object toevoegen</button></div></div>
      {activePallet && <section className="pallet-gallery"><div className="gallery-heading"><div><strong>Palletfoto’s <span className="count-badge">{activePallet.photos?.length || 0}</span></strong><p>Bewaar meerdere beelden van deze pallet.</p></div><div className="gallery-actions"><label className="button secondary"><Icon type="camera"/> Foto maken<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={busy} onChange={e => { addPhotos(activePallet.id, Array.from(e.target.files)); e.target.value = ''; }}/></label><label className="button secondary"><Icon type="upload"/> Foto’s toevoegen<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e => { addPhotos(activePallet.id, Array.from(e.target.files)); e.target.value = ''; }}/></label></div></div>{activePallet.photos?.length ? <div className="photo-gallery">{activePallet.photos.map((photo, index) => <figure key={photo.id}><button className="photo-thumbnail" aria-label={`Foto ${index + 1} van ${activePallet.name} bekijken`} onClick={() => setViewingPhoto({ photos: activePallet.photos, initialIndex: index, palletName: activePallet.name })}><img src={photo.url} alt={`Foto ${index + 1} van ${activePallet.name}`} loading="lazy"/></button><figcaption><span>Foto {index + 1}</span><button className="delete-button" disabled={busy} aria-label={`Foto ${index + 1} van ${activePallet.name} verwijderen`} onClick={() => { setDeletingPhoto({ ...photo, label: `Foto ${index + 1} van ${activePallet.name}` }); setError(''); setModal('deletePhoto'); }}>Verwijderen</button></figcaption></figure>)}</div> : <p className="gallery-empty">Nog geen foto’s. Maak een foto of selecteer bestanden om toe te voegen.</p>}</section>}
      <div className="table-toolbar"><div className="search-controls"><input className="search" type="search" aria-label="Materiaal zoeken" placeholder="Zoek op naam, nummer, artikel of opmerking…" value={search} onChange={e => setSearch(e.target.value)}/>{search && <button className="icon-button" aria-label="Zoekopdracht wissen" onClick={() => setSearch('')}><Icon type="close" size={16}/></button>}</div><label className="sort-controls">Sorteren<select aria-label="Objecten sorteren" value={sortOrder} onChange={e => setSortOrder(e.target.value)}><option value="nameAsc">Naam A–Z</option><option value="nameDesc">Naam Z–A</option><option value="added">Toevoegvolgorde</option></select></label><details className="column-picker"><summary>Trackingkolommen</summary><div>{stages.map(([key, label]) => <label key={key}><input type="checkbox" checked={(data.columns || defaultColumns)[key]} disabled={busy} onChange={e => toggleColumn(key, e.target.checked)}/>{label}</label>)}<small>Jouw weergave voor deze shipment</small></div></details></div>
      <div className="table-scroll"><table><thead><tr><th>Object</th><th>Pallet</th>{visibleStages.map(([key, label]) => <th className="status-column" key={key}>{label}</th>)}<th>Acties</th></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td><div className="object-name">{item.displayName}</div><div className="object-meta">{item.code || 'Geen artikelnummer'}</div>{item.note && <div className="object-note">{item.note}</div>}</td><td><select className="pallet-select" value={item.palletId || ''} disabled={busy} aria-label={`Pallet voor ${item.displayName}`} onChange={e => patchItem(item.id, { palletId: e.target.value || null })}><option value="">Niet toegewezen</option>{data.pallets.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></td>{visibleStages.map(([key, label]) => <td className="status-cell" key={key}><label title={item.statuses[key] ? formatDate(item.statuses[key]) : label}><input type="checkbox" checked={!!item.statuses[key]} disabled={busy} aria-label={`${label}: ${item.displayName}`} onChange={e => patchItem(item.id, { status: key, checked: e.target.checked })}/>{item.statuses[key] && <small>{formatDate(item.statuses[key])}</small>}</label></td>)}<td><div className="object-actions"><button className="secondary" disabled={busy} aria-label={`Bewerken: ${item.displayName}`} onClick={() => openItemModal(item, 'editItem')}>Bewerken</button><button className="delete-button" disabled={busy} aria-label={`Verwijderen: ${item.displayName}`} onClick={() => openItemModal(item, 'deleteItem')}>Verwijderen</button></div></td></tr>)}</tbody></table></div>
      {!filtered.length && <div className="empty-table"><Icon size={34}/><h3>{loading ? 'Materiaal laden…' : search ? 'Geen objecten gevonden' : 'Nog geen materiaal'}</h3><p>{search ? 'Probeer een andere zoekterm.' : activePallet ? 'Wijs objecten toe aan deze pallet of voeg nieuw materiaal toe.' : 'Importeer je materiaallijst of voeg een object manueel toe.'}</p></div>}<div className="table-footer"><span>{filtered.length} objecten zichtbaar</span><span>Elke checkbox wordt automatisch opgeslagen</span></div></section></div>}
      </>}
      <footer className="page-footer">Palletshipper <span>Een overzichtelijke reis voor je materiaal.</span></footer></div>
    </main>
    {viewingPhoto && <PhotoViewer {...viewingPhoto} onClose={closePhotoViewer}/>}
    {modal === 'export' && shipment && <Modal title={`Shipment exporteren: ${shipment.name}`} close={() => { if (!busy) setModal(null); }}><p className="import-explanation">Exporteer de volledige shipment in één keer: {data.pallets.length} palletten en {data.items.length} objecten. Zoekfilters en de geselecteerde pallet beperken de export niet.</p><div className="shipment-export-options"><a className="button secondary" href={`/api/shipments/${selected}/export?format=xlsx`}>Excel — tabblad per pallet</a><a className="button secondary" href={`/api/shipments/${selected}/export?format=csv`}>CSV — volledige shipment</a><a className="button secondary" target="_blank" rel="noreferrer" href={`/api/shipments/${selected}/export?format=print`}>Alle palletlijsten / PDF</a>{data.pallets.length > 0 ? <a className="button primary" target="_blank" rel="noreferrer" href={`/api/shipments/${selected}/export?format=label`}>Alle A6-labels / PDF</a> : <button className="primary" disabled>Maak eerst een pallet voor labels</button>}</div>{unassigned > 0 && <p className="form-hint export-unassigned">{unassigned} objecten zijn nog niet toegewezen. Ze worden apart opgenomen in de materiaallijsten, zonder palletlabel.</p>}<p className="import-explanation">De materiaallijsten gebruiken jouw zichtbare trackingkolommen. Elk palletlabel komt op een eigen A6-pagina.</p>{error && <p className="form-error" role="alert">{error}</p>}</Modal>}
    {modal === 'editItem' && editingItem && <Modal title={`Bewerken: ${editingItem.displayName}`} close={() => { if (!busy) setModal(null); }}><form onSubmit={e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { const item = await api(`/api/items/${editingItem.id}`, { method: 'PATCH', body: { ...body, revision: editingItem.revision } }); setData(current => ({ ...current, items: current.items.map(i => i.id === item.id ? item : i) })); setModal(null); }); }}><label>Omschrijving<input name="name" required maxLength="200" autoFocus defaultValue={editingItem.name}/></label><label>Artikelnummer<input name="code" maxLength="200" defaultValue={editingItem.code}/></label><label>Pallet<select name="palletId" defaultValue={editingItem.palletId || ''}><option value="">Niet toegewezen</option>{data.pallets.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Opmerking<textarea name="note" maxLength="1000" rows="3" defaultValue={editingItem.note}/></label><p className="form-hint">Tracking blijft behouden. Als het volgnummer bij de nieuwe omschrijving al gebruikt is, krijgt dit object het volgende vrije nummer.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={() => setModal(null)}>Annuleren</button><button className="primary" disabled={busy}>{busy ? 'Opslaan…' : 'Wijzigingen opslaan'}</button></div></form></Modal>}
    {modal === 'deleteItem' && editingItem && <Modal title="Object verwijderen" close={() => { if (!busy) setModal(null); }}><p className="delete-explanation">Wil je <strong>{editingItem.displayName}</strong> definitief verwijderen? Ook de tracking van dit object wordt verwijderd.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Annuleren</button><button className="danger" disabled={busy} onClick={() => run(async () => { await api(`/api/items/${editingItem.id}`, { method: 'DELETE', body: { revision: editingItem.revision } }); setData(current => ({ ...current, items: current.items.filter(i => i.id !== editingItem.id) })); setModal(null); })}>{busy ? 'Verwijderen…' : 'Definitief verwijderen'}</button></div></Modal>}
    {modal === 'renamePallet' && editingPallet && <Modal title="Pallet hernoemen" close={() => { if (!busy) setModal(null); }}><form onSubmit={e => { e.preventDefault(); const name = new FormData(e.currentTarget).get('name'); run(async () => { await api(`/api/pallets/${editingPallet.id}`, { method: 'PATCH', body: { name, revision: editingPallet.revision } }); await reload(); setModal(null); }); }}><label>Palletnaam<input name="name" required maxLength="200" autoFocus defaultValue={editingPallet.name}/></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={() => setModal(null)}>Annuleren</button><button className="primary" disabled={busy}>Naam opslaan</button></div></form></Modal>}
    {modal === 'deletePallet' && editingPallet && <Modal title="Pallet verwijderen" close={() => { if (!busy) setModal(null); }}><p className="delete-explanation">Wil je <strong>{editingPallet.name}</strong> verwijderen? De {data.items.filter(i => i.palletId === editingPallet.id).length} objecten komen bij <strong>Nog te verdelen</strong>, met behoud van hun tracking. De palletfoto’s en pallettracking worden definitief verwijderd.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Annuleren</button><button className="danger" disabled={busy} onClick={() => run(async () => { await api(`/api/pallets/${editingPallet.id}`, { method: 'DELETE', body: { revision: editingPallet.revision } }); if (pallet === editingPallet.id) setPallet('unassigned'); await reload(); setModal(null); })}>Pallet definitief verwijderen</button></div></Modal>}
    {modal === 'deletePhoto' && deletingPhoto && <Modal title="Foto verwijderen" close={() => { if (!busy) setModal(null); }}><p className="delete-explanation">Wil je <strong>{deletingPhoto.label}</strong> definitief verwijderen?</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="secondary" disabled={busy} onClick={() => setModal(null)}>Annuleren</button><button className="danger" disabled={busy} onClick={() => run(async () => { await api(`/api/pallets/${deletingPhoto.palletId}/photos/${deletingPhoto.id}`, { method: 'DELETE' }); await reload(); setModal(null); })}>{busy ? 'Verwijderen…' : 'Definitief verwijderen'}</button></div></Modal>}
    {modal === 'users'  && user.role === 'admin' && <Modal title="Gebruikersbeheer" wide close={() => setModal(null)}><UserManager onAccountUpdated={refresh}/></Modal>}
    {modal === 'settings' && shipment?.canManage && <Modal title={`Shipmentinstellingen: ${shipment.name}`} close={() => { if (!busy) setModal(null); }}>
      <section className="settings-section"><h3>Naam en locatie</h3><form key={shipment.id + shipment.name + shipment.destination} onSubmit={e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { const updated = await api(`/api/shipments/${selected}`, { method: 'PATCH', body: { ...body, revision: shipment.revision } }); setShipments(current => current.map(s => s.id === updated.id ? updated : s)); setModal(null); }); }}><label>Shipmentnaam<input name="name" required maxLength="200" defaultValue={shipment.name}/></label><div className="form-grid"><label>Outbound destination<input name="destination" maxLength="200" defaultValue={shipment.destination}/></label><label>Outbound date<input name="outboundDate" type="date" defaultValue={shipment.outboundDate || ''}/></label><label>Return destination<input name="returnDestination" maxLength="200" defaultValue={shipment.returnDestination || ''}/></label><label>Return date<input name="returnDate" type="date" defaultValue={shipment.returnDate || ''}/></label></div><button className="primary" disabled={busy}>Naam en locatie opslaan</button></form></section>
      <section className="settings-section"><h3>Shipmentlogo</h3><p className="import-explanation">Dit logo verschijnt op de A6-labels en palletlijsten.</p>{shipment.canManage && <div className="logo-controls">{data.hasLogo && <img src={`/api/shipments/${selected}/logo`} alt="Shipmentlogo"/>}<label className="button secondary">{data.hasLogo ? 'Logo wijzigen' : 'Eigen logo toevoegen'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e => { const file = e.target.files[0]; e.target.value = ''; if (file) run(async () => { if (file.size > 2 * 1024 * 1024) throw new Error('Het logo mag maximaal 2 MB zijn.'); const body = new FormData(); body.append('file', file); await api(`/api/shipments/${selected}/logo`, { method: 'POST', body }); setLogoVersion(value => value + 1); await reload(); }); }}/></label>{data.hasLogo && <button className="delete-button" disabled={busy} onClick={() => run(async () => { await api(`/api/shipments/${selected}/logo`, { method: 'DELETE' }); await reload(); })}>Standaardlogo gebruiken</button>}</div>}</section>
      <section className="settings-section"><h3>Gebruikersrechten</h3><p className="import-explanation">Bepaal wie deze shipment mag zien en bijwerken.</p><button className="secondary" disabled={busy} onClick={() => setModal('access')}>Gebruikersrechten beheren</button></section>
      <section className="settings-section"><h3>{shipment.archivedAt ? 'Archief' : 'Archiveren'}</h3><p className="import-explanation">Een gearchiveerde shipment blijft beschikbaar via het archief. Foto’s worden verkleind tot maximaal 1600 pixels en gecomprimeerd. De originele fotokwaliteit wordt bij herstellen niet teruggezet.</p><button className="secondary" disabled={busy} onClick={() => run(async () => { const archived = !shipment.archivedAt; await api(`/api/shipments/${selected}`, { method: 'PATCH', body: { archived, revision: shipment.revision } }); await refreshShipments(archived); setModal(null); })}>{busy ? 'Bezig…' : shipment.archivedAt ? 'Shipment herstellen' : 'Shipment archiveren'}</button></section>
      <section className="settings-section"><h3>Shipment verwijderen</h3><p className="import-explanation">Verwijdert de shipment met alle palletten, objecten, foto’s en tracking definitief.</p><button className="danger" disabled={busy} onClick={() => { setError(''); setModal('deleteShipment'); }}>Shipment verwijderen</button></section>
      {error && <p className="form-error" role="alert">{error}</p>}
    </Modal>}
    {modal === 'deleteShipment' && shipment?.canManage && <Modal title="Shipment definitief verwijderen" close={() => { if (!busy) setModal('settings'); }}><p className="delete-explanation">Alle gegevens van <strong>{shipment.name}</strong> worden definitief verwijderd. Typ de shipmentnaam om te bevestigen.</p><form onSubmit={e => { e.preventDefault(); const confirmName = new FormData(e.currentTarget).get('confirmName'); run(async () => { await api(`/api/shipments/${selected}`, { method: 'DELETE', body: { confirmName, revision: shipment.revision } }); await refreshShipments(); setData({ pallets: [], items: [] }); setModal(null); }); }}><label>Shipmentnaam<input name="confirmName" required autoComplete="off"/></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={() => setModal('settings')}>Annuleren</button><button className="danger" disabled={busy}>Definitief verwijderen</button></div></form></Modal>}
    {modal === 'access' && shipment?.canManage && <Modal title={`Toegang tot ${shipment.name}`} close={() => setModal('settings')}><ShipmentAccess shipment={shipment} close={() => setModal('settings')}/></Modal>}
    {modal === 'password' && <Modal title="Wachtwoord wijzigen" close={() => setModal(null)}><PasswordForm onAccountUpdated={refresh} close={() => setModal(null)}/></Modal>}
    {['shipment', 'pallet', 'item'].includes(modal) && <Modal title={modal === 'shipment' ? 'Nieuwe shipment' : modal === 'pallet' ? 'Palletten toevoegen' : 'Object toevoegen'} close={() => { if (!busy) setModal(null); }}><form onSubmit={e => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { if (modal === 'shipment') { const result = await api('/api/shipments', { method: 'POST', body: values }); setShowArchived(false); setShipments(current => [result, ...current]); changeShipment(result.id); } else if (modal === 'pallet') { const result = await api(`/api/shipments/${selected}/pallets`, { method: 'POST', body: values }); await reload(); setPallet(result.id); } else { await api(`/api/shipments/${selected}/items`, { method: 'POST', body: { rows: [values] } }); await reload(); } setModal(null); }); }}>{modal === 'pallet' ? <><label>Aantal palletten<input name="quantity" type="number" min="1" max="200" step="1" required autoFocus value={palletQuantity} onChange={e => setPalletQuantity(e.target.value)}/></label><p className="form-hint">{Number.isInteger(Number(palletQuantity)) && Number(palletQuantity) >= 1 && Number(palletQuantity) <= 200 ? `Automatische nummering: Pallet ${nextPalletNumber(data.pallets)}${Number(palletQuantity) > 1 ? ` tot Pallet ${nextPalletNumber(data.pallets) + Number(palletQuantity) - 1}` : ''}.` : 'Kies 1 tot 200 palletten.'}</p></> : <label>{modal === 'item' ? 'Omschrijving' : 'Naam'}<input name="name" required maxLength="200" autoFocus placeholder={modal === 'shipment' ? 'Bijv. Beurs Antwerpen' : 'Bijv. LED-scherm'}/></label>}{modal === 'shipment' && <div className="form-grid"><label>Outbound destination<input name="destination" maxLength="200" placeholder="Locatie of adres"/></label><label>Outbound date<input name="outboundDate" type="date"/></label><label>Return destination<input name="returnDestination" maxLength="200" placeholder="Warehouse of adres"/></label><label>Return date<input name="returnDate" type="date"/></label></div>}{modal === 'item' && <><div className="form-grid"><label>Artikelnummer<input name="code" maxLength="200"/></label><label>Aantal<input name="quantity" type="number" min="1" max="2000" step="1" defaultValue="1" required/></label></div><p className="form-hint">Elk stuk krijgt een volgnummer achter de naam en eigen tracking.</p><label>Pallet<select name="palletId" defaultValue={activePallet?.id || ''}><option value="">Nog niet toewijzen</option>{data.pallets.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Opmerking<textarea name="note" maxLength="1000" rows="2"/></label></>}{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={() => setModal(null)}>Annuleren</button><button className="primary" disabled={busy}>{busy ? 'Opslaan…' : 'Opslaan'}<Icon type="arrow"/></button></div></form></Modal>}
    {modal === 'import' && preview && <Modal title="Materiaallijst controleren" wide close={() => { if (!busy) setModal(null); }}><p className="import-explanation">Kies de juiste kolommen en controleer de regels. Elk stuk krijgt zijn eigen tracking.</p>{preview.warning && <div className="warning">{preview.warning}</div>}<div className="mapping"><label><input type="checkbox" checked={hasHeader} onChange={e => { setHasHeader(e.target.checked); mapImport(preview, columns, e.target.checked); }}/> Eerste regel bevat kolomnamen</label><div className="form-grid mapping-columns">{[['name','Omschrijving'],['code','Artikelnummer'],['quantity','Aantal']].map(([key,label]) => <label key={key}>{label}<select value={columns[key]} onChange={e => updateMapping(key, e.target.value)}>{key !== 'name' && <option value="-1">{key === 'quantity' ? 'Altijd 1' : 'Geen'}</option>}{Array.from({ length: Math.max(...preview.rows.map(r => r.length)) }, (_,i) => <option key={i} value={i}>Kolom {i + 1}: {preview.rows[0][i]?.slice(0,40)}</option>)}</select></label>)}</div></div><div className="import-table"><table><thead><tr><th>Omschrijving</th><th>Artikelnummer</th><th>Aantal</th><th/></tr></thead><tbody>{importRows.map((row, index) => <tr key={index}><td><input aria-label={`Omschrijving regel ${index + 1}`} value={row.name} onChange={e => setImportRows(current => current.map((r,i) => i === index ? { ...r, name: e.target.value } : r))}/></td><td><input aria-label={`Artikelnummer regel ${index + 1}`} value={row.code} onChange={e => setImportRows(current => current.map((r,i) => i === index ? { ...r, code: e.target.value } : r))}/></td><td><input aria-label={`Aantal regel ${index + 1}`} type="number" min="1" max="2000" step="1" value={row.quantity} onChange={e => setImportRows(current => current.map((r,i) => i === index ? { ...r, quantity: e.target.value } : r))}/></td><td><button className="icon-button" aria-label={`Regel ${index + 1} verwijderen`} onClick={() => setImportRows(current => current.filter((_, i) => i !== index))}><Icon type="close" size={16}/></button></td></tr>)}</tbody></table></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><span>{importRows.length} regels · {importTotal} objecten</span><button className="primary" disabled={busy || !importRows.length || importTotal > 2000 || importRows.some(r => !r.name.trim() || !Number.isInteger(Number(r.quantity)) || Number(r.quantity) < 1)} onClick={() => run(async () => { await api(`/api/shipments/${selected}/items`, { method: 'POST', body: { rows: importRows } }); await reload(); setPallet('unassigned'); setModal(null); })}>{busy ? 'Importeren…' : 'Materiaal importeren'}<Icon type="arrow"/></button></div></Modal>}
  </div>;
}
createRoot(document.getElementById('root')).render(<AuthGate>{props => <App {...props}/>}</AuthGate>);
